name: Dispatch Release
on:
  repository_dispatch:
    types:
      - release-spacedf-docs

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Client payload
        run: |
          cat <<'EOF'
          ${{ toJson(github.event.client_payload) }}
          EOF

      - name: Release
        if: ${{ github.event.client_payload.release_target_commitish == 'main' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.client_payload.release_tag }}
          body: ${{ github.event.client_payload.release_body }}
          target_commitish: 'main'